feat: Проставление тэга/хэша
При сборке в GithubActions проставляется тэг, при локальной сборке проставляется наименование ветки и короткий хэш коммита

diff --git a/.github/workflows/deb_packaging.yml b/.github/workflows/deb_packaging.yml
--- a/.github/workflows/deb_packaging.yml
+++ b/.github/workflows/deb_packaging.yml
@@ -5,15 +5,34 @@ on:
     types:
       - published
 
+env:
+  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
 jobs:
   deb-build:
     runs-on: ubuntu-latest
+
     steps:
+    - name: Debug GitHub Actions environment
+      run: |
+        echo "GITHUB_REF: ${{ github.ref_name }}"
+          
     - name: Checkout
       uses: actions/checkout@v3
       with:
         ref: ${{ github.sha }}
-      
+        
+    - name: Set AppName
+      run: |
+        file_path=$(find . -type f -name "AppNameDefinitionService.cs")
+        
+        if [ -n "$file_path" ]; then
+         sed -i 's/AppName = "ReleaseTag";/AppName = "${{ github.ref_name }}";/g' "$file_path"
+        else
+         echo "File not found."
+         exit 1
+        fi
+
     - name: Generate DebPkg
       run: sh ./src/Unlimotion.Desktop/ci/deb/generate-deb-pkg.sh ${{  github.ref_name }}
 
diff --git a/.github/workflows/msi_packaging.yml b/.github/workflows/msi_packaging.yml
--- a/.github/workflows/msi_packaging.yml
+++ b/.github/workflows/msi_packaging.yml
@@ -5,15 +5,34 @@ on:
     types:
       - published
 
+env:
+  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
 jobs:
   advinst-aip-build:
     runs-on: windows-2022
+
     steps:
+    - name: Debug GitHub Actions environment
+      run: |
+        echo "GITHUB_REF: ${{ github.ref_name }}"
+        
     - name: Checkout
       uses: actions/checkout@v3
       with:
         ref: ${{ github.sha }}
+        
+    - name: Set AppName
+      run: |
+        $filePath = Get-ChildItem -Path . -Recurse -Filter "AppNameDefinitionService.cs" | Select-Object -ExpandProperty FullName
 
+        if ($filePath) {
+          (Get-Content -Path $filePath) -replace 'ReleaseTag', "${{ github.ref_name }}" | Set-Content -Path $filePath
+        } else {
+          Write-Error "File not found."
+          exit 1
+        }
+        
     - name: Publish
       run: dotnet publish src\Unlimotion.Desktop\Unlimotion.Desktop.csproj -c Release -f net7.0 -r win-x64 -o ${{ github.workspace }}\src\Unlimotion.Desktop\bin\Release\net7.0\win-x64\publish -p:PublishSingleFile=true --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=None -p:DebugSymbols=false -p:Version=${{  github.ref_name }}
 
@@ -35,5 +54,3 @@ jobs:
       with:
         file: ${{ github.workspace }}\setup\Unlimotion-${{  github.ref_name }}.msi
         tags: true
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
diff --git a/.github/workflows/osx-packaging.yml b/.github/workflows/osx-packaging.yml
--- a/.github/workflows/osx-packaging.yml
+++ b/.github/workflows/osx-packaging.yml
@@ -5,25 +5,45 @@ on:
     types:
       - published
 
+env:
+  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
 jobs:
   osx-build:
     runs-on: macos-latest
+
     steps:
+    - name: Debug GitHub Actions environment
+      run: |
+        echo "GITHUB_REF: ${{ github.ref_name }}"
+        
     - name: Checkout
       uses: actions/checkout@v3
       with:
         ref: ${{ github.sha }}
+        
+    - name: Set AppName
+      run: |
+        file_path=$(find . -type f -name "AppNameDefinitionService.cs" -print -quit)
+  
+        if [ -n "$file_path" ]; then
+          sed -i '' 's/ReleaseTag/${{ github.ref_name }}/g' "$file_path"
+          echo "Replacement completed successfully."
+        else
+          echo "File not found."
+          exit 1
+        fi
 
     - name: Publish
-      run: sh ./src/Unlimotion.Desktop/ci/osx/generate-osx-publish.sh ${{  github.ref_name }}
+      run: sh ./src/Unlimotion.Desktop/ci/osx/generate-osx-publish.sh ${{ github.ref_name }}
 
     - name: Generate App
-      run: sh ./src/Unlimotion.Desktop/ci/osx/generate-osx-app.sh ${{  github.ref_name }}
+      run: sh ./src/Unlimotion.Desktop/ci/osx/generate-osx-app.sh ${{ github.ref_name }}
 
     - name: Generate Pkg
-      run: sh ./src/Unlimotion.Desktop/ci/osx/generate-osx-pkg.sh ${{  github.ref_name }}
+      run: sh ./src/Unlimotion.Desktop/ci/osx/generate-osx-pkg.sh ${{ github.ref_name }}
 
     - name: Upload MacOSPkg To Release
       uses: softprops/action-gh-release@v1
       with:
-        files: ./*.pkg	
+        files: ./*.pkg
