Проверка Common Steps

diff --git a/.github/workflows/msi_packaging.yml b/.github/workflows/msi_packaging.yml
--- a/.github/workflows/msi_packaging.yml
+++ b/.github/workflows/msi_packaging.yml
@@ -13,25 +13,24 @@ jobs:
     runs-on: windows-2022
 
     steps:
-    - name: Debug GitHub Actions environment
-      run: |
-        echo "GITHUB_REF: ${{ github.ref_name }}"
-        
     - name: Checkout
       uses: actions/checkout@v3
       with:
         ref: ${{ github.sha }}
         
+    - name: Debug Ref Name
+      uses: ./.github/actions/common-steps
+        
     - name: Set AppName
       run: |
-        $filePath = Get-ChildItem -Path . -Recurse -Filter "AppNameDefinitionService.cs" | Select-Object -ExpandProperty FullName
-
-        if ($filePath) {
-          (Get-Content -Path $filePath) -replace 'ReleaseTag', "${{ github.ref_name }}" | Set-Content -Path $filePath
-        } else {
-          Write-Error "File not found."
-          exit 1
-        }
+        file_path=$(find . -type f -name "AppNameDefinitionService.cs")
+        
+        if [ -n "$file_path" ]; then
+         sed -i 's/AppName = "ReleaseTag";/AppName = "${{ github.ref_name }}";/g' "$file_path"
+        else
+         echo "File not found."
+         exit 1
+        fi
         
     - name: Publish
       run: dotnet publish src\Unlimotion.Desktop\Unlimotion.Desktop.csproj -c Release -f net7.0 -r win-x64 -o ${{ github.workspace }}\src\Unlimotion.Desktop\bin\Release\net7.0\win-x64\publish -p:PublishSingleFile=true --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=None -p:DebugSymbols=false -p:Version=${{  github.ref_name }}
